config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
# app/controllers/todos_controller.rb

class TodosController < ApplicationController
  before_action :set_todo, only: %i[show edit update destroy]

  def index
    @todos = Todo.all
  end

  def show; end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to todos_path, notice: 'ToDo was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @todo.update(todo_params)
      redirect_to todos_path, notice: 'ToDo was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_path, notice: 'ToDo was successfully destroyed.'
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: @todo, local: true) do |form| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@todo.errors.count, 'error') %> prohibited this todo from being saved:</h2>

      <ul>
        <% @todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/todos/create.html.erb
<h1>Todos#create</h1>
<p>Find me in app/views/todos/create.html.erb</p>

app/views/todos/destroy.html.erb
<h1>Todos#destroy</h1>
<p>Find me in app/views/todos/destroy.html.erb</p>

app/views/todos/edit.html.erb
<div class="container mt-4">
  <h1><%= action_name.capitalize %> ToDo</h1>

  <%= render 'form' %>

  <%= link_to 'Back', todos_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/todos/index.html.erb
<div class="container mt-4">
  <div class="d-flex justify-content-between">
    <div>
      <h1 class="mb-4">ToDo List</h1>
    </div>
    <div>
      <%= link_to 'New ToDo', new_todo_path, class: 'btn btn-success' %>
    </div>
  </div>

  <div class="row">
    <% @todos.each do |todo| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= todo.title %></h5>
            <p class="card-text"><%= truncate(todo.description, length: 100) %></p>
            <p class="card-text"><small class="text-muted">Created at: <%= todo.created_at %></small></p>
            <p class="card-text"><small class="text-muted">Updated at: <%= todo.updated_at %></small></p>

            <!-- Edit button -->
            <%= link_to 'Edit', edit_todo_path(todo), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Details', todo_path(todo), class: 'btn btn-primary btn-sm' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/todos/new.html.erb
<div class="container mt-4">
  <h1><%= action_name.capitalize %> ToDo</h1>

  <%= render 'form' %>

  <%= link_to 'Back', todos_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/todos/show.html.erb
<div class="container mt-4">
  <h1><%= @todo.title %></h1>

  <div class="card">
    <div class="card-body">
      <p class="card-text"><strong>Description:</strong></p>
      <p class="card-text"><%= simple_format(@todo.description) %></p>
      <p class="card-text"><strong>Created at:</strong> <%= @todo.created_at %></p>
      <p class="card-text"><strong>Updated at:</strong> <%= @todo.updated_at %></p>

      <!-- Edit button -->
      <%= link_to 'Edit', edit_todo_path(@todo), class: 'btn btn-warning mt-3' %>
    </div>
  </div>

  <%= link_to 'Back', todos_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/todos/update.html.erb
<h1>Todos#update</h1>
<p>Find me in app/views/todos/update.html.erb</p>